#!/usr/bin/env python3
"""spec_map.py — displacement map for D1-flagged normalization records (SEC-023).

For every record whose "Normalized" text fails the rule-identity check (D1 in
spec_check.py), find which record's "Original" quotation the Normalized text
best matches.  That yields a mechanical classification:

  DISPLACED->X   the Normalized text denotes record X's rule (rotation proof)
  WEAKENED       best match is still its own Original -> heavy rewrite that
                 lost the rule's distinctive content (security-relevant)
  UNMATCHED      no Original matches -> invented or foreign text

Also emits the restoration source for each flagged record (its own Original).

Usage: python3 audit/spec_map.py [--draft OUT.md]
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from spec_check import MIN_OVERLAP, parse_records, signature, overlap  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
DRAFT_DEFAULT = REPO / "audit" / "spec01-restoration-draft.md"

DISPLACE_MIN = 0.35   # best-other score needed to call DISPLACED->X
UNMATCHED_MAX = 0.20  # below this (and no displacement) -> UNMATCHED


def classify():
    recs = parse_records()
    sigs = {rid: (signature(o), signature(n)) for rid, (o, n) in recs.items()}
    flagged, rows = [], []
    for rid in sorted(recs):
        s_o, s_n = sigs[rid]
        self_score = overlap(s_o, s_n)
        if self_score >= MIN_OVERLAP:
            continue
        flagged.append(rid)
        best_other, best_sc = None, 0.0
        for oid in sorted(recs):
            if oid == rid:
                continue
            sc = overlap(s_n, sigs[oid][0])
            if sc > best_sc:
                best_other, best_sc = oid, sc
        if best_sc >= DISPLACE_MIN:
            cls = f"DISPLACED->{best_other}"
        elif best_sc <= UNMATCHED_MAX:
            cls = "UNMATCHED"
        else:
            cls = f"WEAKENED (nearest {best_other} {best_sc:.2f})"
        rows.append((rid, self_score, best_other or "-", best_sc, cls))
    return recs, rows


def main() -> int:
    ap = sys.argv[1:]
    draft_path = DRAFT_DEFAULT
    if "--draft" in ap:
        draft_path = Path(ap[ap.index("--draft") + 1])

    recs, rows = classify()
    n = len(rows)
    displaced = [r for r in rows if r[4].startswith("DISPLACED")]
    weakened = [r for r in rows if r[4].startswith("WEAKENED")]
    unmatched = [r for r in rows if r[4] == "UNMATCHED"]

    print(f"flagged records: {n}")
    print(f"  DISPLACED (rotation proven): {len(displaced)}")
    print(f"  WEAKENED  (rewrite, own rule nearest): {len(weakened)}")
    print(f"  UNMATCHED (invented/foreign text):  {len(unmatched)}")
    print()
    for rid, self_sc, near, near_sc, cls in rows:
        print(f"  {rid:14s} self={self_sc:.2f}  nearest={near:14s} {near_sc:.2f}  {cls}")

    if "--draft" in ap or "--write-draft" in ap or True:
        # The draft is cheap and deterministic; always (re)write it.
        with open(draft_path, "w", encoding="utf-8") as f:
            w = f.write
            w("# SEC-023 restoration draft — `spec/01` obligation bodies\n\n")
            w("**Status: DRAFT FOR SPECIFICATION-OWNER ADOPTION — not applied.** This file\n")
            w("changes no frozen text. Per R-SCOPE-03 the substitution must be reversed by\n")
            w("an explicit frozen addendum; this draft is the mechanical input for it.\n\n")
            w("Generated by `audit/spec_map.py` from `spec/normative-normalization-records.md`\n")
            w("(each record's own **Original** quotation is the restoration text — the rule\n")
            w("the stable ID denotes per `spec/03`, `spec/08`, `mod/`, and `req/`).\n\n")
            w(f"Flagged: **{n} of 148** records — {len(displaced)} DISPLACED, "
              f"{len(weakened)} WEAKENED, {len(unmatched)} UNMATCHED.\n\n")
            w("## 1. Displacement map\n\n")
            w("| Obligation | self | nearest Original | score | Classification |\n")
            w("|---|---|---|---|---|\n")
            for rid, self_sc, near, near_sc, cls in rows:
                w(f"| {rid} | {self_sc:.2f} | {near} | {near_sc:.2f} | {cls} |\n")
            w("\n## 2. Restoration text per flagged obligation\n\n")
            w("For each: the **current substituted body** (quoted, not deleted — the\n")
            w("repository's own supersession discipline) and the **restoration text**\n")
            w("(the record's Original). Adoption should also re-verify against the\n")
            w("corresponding `req/` area file, which this audit confirmed intact.\n\n")
            w("---\n\n")
            for rid, self_sc, near, near_sc, cls in rows:
                orig, norm = recs[rid]
                orig_flat = " ".join(orig.replace("> ", "").split())
                norm_flat = " ".join(norm.replace("> ", "").split())
                w(f"### {rid} — {cls}\n\n")
                w(f"**Current `spec/01`-layer text (substituted; quoted):**\n\n")
                w(f"> {norm_flat}\n\n")
                w(f"**Restoration text (the rule the ID denotes, from the record's Original):**\n\n")
                w(f"> {orig_flat}\n\n")
                w(f"*Self-overlap {self_sc:.2f}; nearest foreign Original {near} ({near_sc:.2f}).*\n\n---\n\n")
            w("## 3. Adoption procedure\n\n")
            w("1. Specification owner reviews each block above against `req/` and the\n")
            w("   cited `Red-on-Rust.md` lines (both confirmed correct by this audit).\n")
            w("2. Apply as a single frozen addendum updating `spec/01` bodies in place,\n")
            w("   with the substituted wording quoted (not silently deleted) per R-SCOPE-03.\n")
            w("3. Re-adjudicate the affected `Semantic Risk` fields in the records.\n")
            w("4. Gate: `python3 audit/spec_check.py` must exit 0 (D1 clean); then promote\n")
            w("   it to `spec/_check.py` so regeneration is blocked on ID->rule drift.\n")
        print(f"\ndraft written: {draft_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
