"""scripts/spec/published.py — the committed derived artifacts under `spec/0…-*/`.

§6 of the transformation instruction requires the repository to expose the
`spec/00-source … spec/05-vectors` layout.  It does, and every file in it is
generated by this module — with one deliberate constraint: **the committed
artifacts are pointers, identity digests and registers, never copies of
normative text.**

Why the constraint (the whole design decision in one paragraph): the repository
already owns the canonical human-readable specification (`spec/01`, compiled for
presentation in `final/01`), and `Red-on-Rust.md` is the frozen source.  Copying
their normative bytes into `spec/01-sections/`, `spec/03-canonical/Red-on-Rust.md`
or `spec/04-audit/*.md` would create two homes for one requirement — duplicate
authority, which §14 makes a verification failure and §20 forbids outright ("the
transformation pipeline MUST NOT create a competing governance system").  So the
committed set carries what a reader needs to *navigate and verify* — the source
digest, per-section digests and identity lists, registry and finding counts, the
vector manifest — while the byte-exact rendered bodies live in the reproducible
build output (`build/spec/`, regenerated identically by
`python3 scripts/spec/pipeline.py`).  Every digest here is the digest of those
rendered bytes, so a reader can prove a projection is current without the
repository holding a second copy of the specification.

Rendered by:  `python3 scripts/spec/pipeline.py --publish-derived`
Checked by:   `python3 scripts/spec/_gate.py` (registered in `check.py`)
"""
from __future__ import annotations

from _common import PIPELINE_NAME, PIPELINE_VERSION, table

NOTICE = ("**DERIVED POINTER — generated by the controlled specification pipeline. Not a normative "
          "source.** The authority for anything summarized here is named in the same row; where a "
          "projection and an authority differ, the authority governs and `scripts/spec/_gate.py` "
          "fails.")

PATHS = ["spec/00-source/README.md", "spec/01-sections/README.md", "spec/02-registry/README.md",
         "spec/03-canonical/README.md", "spec/04-audit/README.md", "spec/05-vectors/README.md",
         "spec/PIPELINE.md"]


def _head(title: str, ctx, run, prov) -> list[str]:
    return [f"# {title}\n\n", NOTICE + "\n\n",
            f"*generated by `{PIPELINE_NAME}` v`{PIPELINE_VERSION}` · stage `{prov['stage']}` · "
            f"seed source `Red-on-Rust.md` @ `sha256:{ctx.source_sha256}` · render "
            f"`{run['render_hash'][:23]}…`*\n\n"]


def render(ctx, run, prov) -> dict:
    import json
    out: dict[str, list] = {}
    f = run["files"]
    S1, S2, S3, S4, S5, S6, S6b, S7 = (run["results"][k]["data"] for k in
                                       ("S1", "S2", "S3", "S4", "S5", "S6", "S6b", "S7"))
    snap = json.loads(f["snapshot.json"])

    # ---------------- spec/00-source --------------------------------------
    o = _head("00-source — Source Snapshot (pointer)", ctx, run, prov)
    o.append("## 1. Frozen source of record\n\n")
    o.append(table([
        ["path", "`Red-on-Rust.md`", "the repository's single normative authority"],
        ["sha256", "`sha256:" + ctx.source_sha256 + "`", "computed by stage S0 (`snapshot.py`)"],
        ["lines", str(ctx.source_line_count), "`spec/10-index.json` meta.source_of_record"],
        ["bytes", str(ctx.source_byte_count), "S0"],
        ["turns", f"{snap['snapshot']['turn_headings']} "
                  f"(`[{snap['snapshot']['turn_range'][0]}]`–`[{snap['snapshot']['turn_range'][1]}]`)",
         "source headings, counted not parsed"],
        ["timestamp", "none", "§4.1 — a stamp would make the snapshot unreproducible"],
    ], ["field", "value", "authority"]))
    o.append("\n## 2. Why this directory holds no copy of the source\n\n")
    o.append("A second byte-identical copy of a frozen normative document is a second authority that "
             "can drift. The snapshot's role — immutable evidence of the input — is served by the "
             "pinned digest, which any reader can re-verify in one command: `sha256sum "
             "Red-on-Rust.md`. The full S0 artifact set (identity, structural measures, and the "
             "cross-checks against `reg/` and `spec/10` pins) renders to `build/spec/source.sha256`, "
             "`build/spec/snapshot.json` and `build/spec/source-snapshot.md`.\n\n")
    o.append("## 3. Snapshot checks (from the current render)\n\n")
    o.append(table([[c["check"], "PASS" if c["pass"] else "FAIL", c["detail"]] for c in snap["checks"]],
                   ["check", "result", "detail"]))
    out[PATHS[0]] = o

    # ---------------- spec/01-sections -------------------------------------
    o = _head("01-sections — Semantic Section Registry (pointer)", ctx, run, prov)
    o.append("The section split is `spec/02-section-hierarchy.md`'s 24 sections (S-01…S-24), "
             "projected byte-exactly from `spec/01-canonical-specification.md` by stage S2 and "
             "verified lossless: the concatenation of the section bodies rebuilds `spec/01`'s section "
             "material exactly (whitespace-normalised), so the split preserves ordering, provenance, "
             "cross references, requirement identity and normative meaning (§9). Cross-reference and "
             "supersession metadata and the byte-exact bodies live in the rendered build output: "
             "`build/spec/sections/S-nn-*.md`, `build/spec/sections/index.md`.\n\n")
    rows = [[s["id"], s["title"], s["part"], s["requirement_count"],
             ", ".join(s["domain_hint"]) or "—", s["source_provenance"], s["body_sha256"][:19] + "…"]
            for s in S2["sections"]]
    o.append(table(rows, ["section", "title", "part", "requirements", "domain hint (§6 vocabulary)",
                          "frozen-source provenance", "body digest"]))
    o.append("\n*`domain hint` is the §6 layout's suggested vocabulary, attached as metadata. It "
             "renames no section and re-homes no requirement: `spec/02` remains the structure "
             "authority and `spec/01` the text authority (§4.5).*\n\n")
    o.append("Split checks in the current render: "
             + "; ".join(c["check"] + " → " + ("PASS" if c["pass"] else "FAIL")
                         for c in S2["checks"]) + ".\n")
    out[PATHS[1]] = o

    # ---------------- spec/02-registry -------------------------------------
    o = _head("02-registry — Registry Bindings (pointer)", ctx, run, prov)
    o.append("The pipeline's four registries are **projections of the existing registers**, generated "
             "into `build/spec/` (§20: extend repository governance, do not create a rival registry).\n\n")
    o.append(table([
        ["requirements", "`build/spec/requirements.json`",
         "`spec/03-obligation-matrix.md` (compiled: `reg/requirements.json`)",
         S6["counts"]["requirements"]],
        ["obligations", "`build/spec/obligations.json`", "`spec/03` + `req/registry.json` (atomic layer)",
         f"{S6['counts']['obligations']} + {S6['counts']['atomic_records_registered']} atomic"],
        ["terminology", "`build/spec/terminology.json`",
         "`term/10-index.json` (data of record `term/_terms.py`)",
         S6["counts"]["terminology_entries"]],
        ["dependencies", "`build/spec/dependencies.json`",
         "`dep/10-graph.json` + `spec/10-index.json`",
         f"{S6['counts']['section_edges']} section edges"],
    ], ["registry", "rendered file", "authority it copies", "identities"]))
    o.append("\nIdentity set digest (all listed authorities agree): `"
             + S6["identity"]["set_sha256"][:19] + "…` over " + str(S6["identity"]["count"])
             + " IDs. Statuses: `SPECIFIED` for every row — the evidence ceiling (`spec/00` §2). "
             "Registry generation changed " + str(S6["policy"]["identity_changes"]) + " identities, "
             + str(S6["policy"]["status_changes"]) + " statuses, and left "
             + str(S6["policy"]["provenance_gaps"]) + " rows without provenance.\n\n")
    o.append("Atomic reconciliation: " + str(S6["counts"]["atomic_records_cited"]) + " of "
             + str(S6["counts"]["atomic_records_registered"]) + " atomic records are cited by a single "
             "parent; the residue is registered in `req/02-compound-not-split.md` (compound statements "
             "kept whole) — recorded, not repaired.\n\n")
    o.append("`reg/requirements.json` (+ `reg/requirements.schema.json`, `reg/status-transitions.json`) "
             "remains the committed registry of record, and `reg/status-transitions.json` remains the "
             "only channel in which a status may change. This directory adds no second registry of "
             "authority; schemas for the pipeline's own output land in `build/spec/schemas/`.\n")
    out[PATHS[2]] = o

    # ---------------- spec/03-canonical ------------------------------------
    o = _head("03-canonical — Canonical Specification Bindings (pointer)", ctx, run, prov)
    o.append(table([
        ["frozen source", "authority", "`Red-on-Rust.md` @ `sha256:" + ctx.source_sha256[:24] + "…`"],
        ["canonical human-readable specification", "**authority for cleaned text**",
         "`spec/01-canonical-specification.md`"],
        ["compiled presentation set", "derived projection",
         "`final/01-canonical-specification.md` (29 sections)"],
        ["pipeline reconstruction", "derived, generated, gated",
         "`build/spec/Red-on-Rust.canonical.md`"],
    ], ["artifact", "role", "location"]))
    o.append("\n`spec/03-canonical/Red-on-Rust.md` is **not** written. §6 names that path; the "
             "repository already has a canonical specification, and a second file claiming canonical "
             "status at the same level would be duplicate authority — a §14 verification failure by "
             "definition. The pipeline's canonical artifact is therefore the reconstruction in "
             "`build/spec/`, generated from the validated registries, and the gate proves it identical "
             "to `spec/01` chunk-for-chunk.\n\n")
    o.append("Canonicalization record (S5, current render):\n\n")
    o.append(table([
        ["requirements reconstructed", S5["counts"]["requirements"]],
        ["sections", S5["counts"]["sections"]],
        ["introduced by canonicalization", S5["counts"]["introduced"]],
        ["dropped by canonicalization", S5["counts"]["dropped"]],
        ["status promotions", S5["counts"]["promotions"]],
        ["chunk multiset (reconstruction)", "`" + S5["chunk_multiset_sha256"][:19] + "…`"],
        ["chunk multiset (spec/01 authority)", "`" + S5["authority_chunk_multiset_sha256"][:19] + "…`"],
        ["open BLOCKING carried", len(S5["open_blocking"])],
        ["open MAJOR carried", len(S5["open_major"])],
        ["strict mode", S5["policy"]["strict"]],
        ["proposals accepted into canonicalization", S5["safety_theorem"]["proposals_in_this_run"]],
    ], ["measure", "value"]))
    o.append("\nSafety theorem (§17), as enforced: `UntrustedProposal → DeterministicValidation → "
             "ValidatedArtifact → Canonicalization → AuthoritativeProjection`. The direct edge "
             "`UntrustedProposal → CanonicalSpecification` does not exist in the code.\n\n")
    o.append(table([[c["check"], "PASS" if c["pass"] else "FAIL", c["detail"]] for c in S5["checks"]],
                   ["check", "result", "detail"]))
    out[PATHS[3]] = o

    # ---------------- spec/04-audit ----------------------------------------
    o = _head("04-audit — Audit Index (pointer)", ctx, run, prov)
    o.append("The audit register of record is `spec/06-contradictions-ambiguities.md` (C-01…C-115 over "
             "112 findings + the C-39 pointer row), with decisions in "
             "`spec/09-unresolved-decisions.md` (U-01…U-45, " + str(S4["counts"]["spec09_rows"])
             + " registered) and ambiguities in `req/03-ambiguous.md`. This directory indexes the "
             "pipeline's §11 categories in the exact shapes §11 requires (`finding_id`, `category`, "
             "`severity`, source references, affected artifacts, `description`, `proposed_resolution`, "
             "`authority_required`, `status`) and never re-grades a row.\n\n")
    cat_rows = []
    for k, v in sorted(S4["category_evidence"].items()):
        cells = []
        for a, b in sorted(v.items()):
            if isinstance(b, dict):
                cells.append(f"{a}: " + ", ".join(f"{x}:{y}" for x, y in sorted(b.items())))
            elif isinstance(b, list):
                cells.append(f"{a}: {len(b)} item(s)")
            elif isinstance(b, (int, float)):
                cells.append(f"{a}: {b}")
        cat_rows.append([k, " · ".join(cells) or "—"])
    o.append(table(cat_rows, ["category", "measures (from the authority each cites)"]))
    o.append("\nCounts: " + ", ".join(f"`{k}` {v}" for k, v in sorted(S4["counts"].items())) + ".\n\n")
    o.append("The rendered projections are `build/spec/audit/{ambiguities,contradictions,security,"
             "determinism,evidence}.md`, `build/spec/audit/integrity.md` and the per-category files, "
             "with the machine set in `build/spec/audit.json`.\n\n")
    o.append("## Findings the pipeline would file (printed, never filed)\n\n")
    if S4["candidate_findings"]:
        o.append(table([[c["suggested_id"], c["identity"], c["category"], c["severity"],
                         ", ".join(c["documents"]), c["why"]] for c in S4["candidate_findings"]],
                       ["suggested id", "subject", "category", "severity", "documents", "why"]))
    else:
        o.append("_none — every integrity scan came back clean in this render_\n")
    o.append("\nSuggested ids are computed from the registers' own maxima; writing them would be a "
             "governance act. Proposed resolutions are recorded **only** where an authority recorded "
             "one; every other open row reads `none recorded` (§16).\n")
    out[PATHS[4]] = o

    # ---------------- spec/05-vectors --------------------------------------
    o = _head("05-vectors — Evidence Vector Index (pointer)", ctx, run, prov)
    o.append("Registered evidence fixtures, projected (never authored) from the authorities, in the "
             "three families §6 names.\n\n")
    fam_rows = []
    for k, v in sorted(S6b["index"].items()):
        ids = v["vector_ids"]
        fam_rows.append([k, v["count"], v["authority"],
                         ", ".join(ids[:4]) + ("…" if len(ids) > 4 else "")])
    o.append(table(fam_rows, ["family", "vectors", "authority", "ids (pipeline-local, additive)"]))
    o.append("\nEach vector record carries the byte-exact quoted value, its authority document and "
             "line range, a text digest, and `status: SPECIFIED`. Nothing here is a test, a harness or "
             "an implementation: running any of these fixtures requires the Rust code §21 forbids until "
             "M0, so the honest state is *registered, unconsumed*.\n\n")
    o.append("Policy as rendered: `invented_vectors` " + str(S6b["policy"]["invented_vectors"])
             + ", `adjudicated_discrepancies` " + str(S6b["policy"]["adjudicated_discrepancies"])
             + ", `source_lines_rewritten` " + str(S6b["policy"]["source_lines_rewritten"]) + ".\n\n")
    o.append("Where the frozen source carries a byte form the canonical rendering does not (the stale "
             "standalone tags registered as `spec/06` C-02), the difference is listed in "
             "`build/spec/vectors/canonical.json → discrepancies` for the authority to decide — not "
             "repaired.\n")
    out[PATHS[5]] = o

    # ---------------- spec/PIPELINE.md -------------------------------------
    o = _head("Red-on-Rust — Controlled Specification-Processing Pipeline", ctx, run, prov)
    o.append("**Version 1.0 · mode: specification-processing infrastructure only · M0: `NOT STARTED` "
             "· no Rust implementation, no runtime, no test harness (§21).**\n\n")
    o.append("The repository's executable contract for transforming its own specification. The LLM — "
             "and this generator — is a proposal engine inside a deterministic governance machine: it "
             "may propose, it may not authorize (§23).\n\n")
    o.append("## 1. Pipeline\n\n```\n")
    o.append("RAW SEED SOURCE  Red-on-Rust.md\n")
    o.append("  ↓ S0 SNAPSHOT      identity + provenance      -> source.sha256, snapshot.json\n")
    o.append("  ↓ S1 EXTRACT       requirement/obligation candidates, normative class, proposals.json\n")
    o.append("  ↓ S2 SPLIT         sections (lossless, spec/02 order)\n")
    o.append("  ↓ S3 NORMALIZE     terminology / predicate / identifier registration (no rewriting)\n")
    o.append("  ↓ S4 AUDIT         16 categories · findings projected · integrity scans\n")
    o.append("  ↓ S5 CANONICALIZE  reconstruction ⊆ NormativeContent(spec/01)\n")
    o.append("  ↓ S6 REGISTER      requirements · obligations · terminology · dependencies\n")
    o.append("  ↓ S6b VECTORS      registered fixtures (canonical / persistence / effects)\n")
    o.append("  ↓ S7 VERIFY        cross-artifact battery over every projection (§14)\n```\n\n")
    o.append("Authority distinction preserved end to end: `SOURCE ≠ PROPOSAL ≠ DERIVED ARTIFACT ≠ "
             "CANONICAL AUTHORITY`.\n\n")
    o.append("## 2. Entry points\n\n```\n")
    o.append("python3 scripts/spec/pipeline.py Red-on-Rust.md          # full pipeline -> build/spec/\n")
    o.append("python3 scripts/spec/pipeline.py Red-on-Rust.md --check  # prove the build set is current\n")
    o.append("python3 scripts/spec/pipeline.py --verify-only           # render + S7 battery, write nothing\n")
    o.append("python3 scripts/spec/pipeline.py --list                  # stages and their contracts\n")
    o.append("python3 scripts/spec/pipeline.py --report                # the §24 transformation report\n")
    o.append("python3 scripts/spec/pipeline.py --publish-derived       # rewrite spec/0*-*/ + PIPELINE.md\n")
    o.append("python3 scripts/spec/pipeline.py --strict                  # refuse to canonicalize over open BLOCKING/MAJOR\n")
    o.append("python3 scripts/spec/_gate.py --strict                     # the same refusal, as a gate proof\n")
    o.append("python3 scripts/spec/_gate.py                            # the repository gate (check.py)\n")
    o.append("python3 tests/spec/_pipeline_mutations.py                # drift-detection battery\n```\n\n")
    o.append("Stage flags (`--snapshot … --verify`, `--all`) select which stage summaries are printed; "
             "every run executes the full ordered pipeline, because a stage that could run alone would "
             "be a stage whose failure the others could not see (§19).\n\n")
    o.append("## 3. Trust model (§3, §17)\n\n```\n")
    o.append("LLM -> proposes extraction / splitting / normalization / terminology / dependencies /\n")
    o.append("      ambiguities  ->  deterministic validators -> PASS: accepted artifact\n")
    o.append("                                              -> FAIL: audit + review\n```\n\n")
    o.append("The proposal channel is not merely unused \u2014 it does not exist. No module on the "
             "render path may open a path containing `proposal`, and S7 scans the render modules for "
             "exactly that, so an intake added later fails the run until validators *and* mutations "
             "exist for it. `proposals.json` therefore reports `accepted_count: 0` as a structural "
             "constant: the evidence is the scan, and the unexercised adjudication path is carried as a "
             "disclosed gap rather than claimed as a pass.\n\n")
    o.append("This pipeline never: defines canonical authority; invents, deletes, merges, splits, "
             "renumbers or re-predicates a requirement; alters a historical record; overwrites a "
             "canonical artifact without validation; or claims verification because something was "
             f"generated. `Canonicalize(X) ⊆ NormativeContent(X)` is enforced by chunk-multiset "
             f"equality (current render: "
             + ("EQUAL" if S5["chunk_multiset_sha256"] == S5["authority_chunk_multiset_sha256"]
                else "NOT EQUAL — gate fails") + ").\n\n")
    o.append("## 4. Invariants honoured (§4)\n\n")
    o.append(table([
        ["provenance", "every artifact names source hash, path, pipeline version, stage, generator and "
                       "inputs; every registry row names where its value was copied from",
         "missing provenance → S7 fails"],
        ["determinism", "no clock, no randomness, no locale, no network, no directory order; sorted "
                        "rendering; JSON `sort_keys`; registry order for lists; the environment report "
                        "names what it ignores instead of echoing a host value",
         "S7 scans the stage sources and fails on an offender; the battery re-renders in separate "
         "interpreters under hash-seed, locale, timezone and cwd variation and requires one content "
         "address"],
        ["idempotence", "`Pipeline(Pipeline(X)) == Pipeline(X)` on canonical content — the reconstruction "
                        "is chunk-identical to `spec/01`; publishing compares bytes before writing",
         "multiset inequality → S5 refuses"],
        ["no normative invention", "generators read registers only; every published cell names its "
                                   "authority", "unregistered identity → S7 fails"],
        ["identity preservation", "`spec/03`'s ID set *and order* are the output's ID set and order",
         "divergence → S7 fails"],
        ["timestamps", "absent from semantic content and from every canonical hash (§4.1)",
         "a `timestamp_present: true` field would fail the schema"],
    ], ["invariant", "mechanism", "failure behaviour"]))
    o.append("\nReproducibility is proven by `render_hash`, a content address over the whole artifact "
             "set (`build/spec/manifest.json`).\n\n")
    o.append("## 5. Fail-closed (§19)\n\n")
    o.append("Any stage failure aborts before a byte is written; verification failure means the "
             "canonical state is not accepted. A failed audit blocks canonicalization under `--strict`; "
             "under the default policy unresolved rows are carried **and disclosed** in the canonical "
             "artifact's open-items section, because dropping them would be the fabricated completeness "
             "§16 prohibits and `spec/01` itself publishes them as open. Carrying is only legitimate "
             "while the row is *visible*: S5 refuses the run if an open row bearing on the canonical "
             "predicate is absent from the disclosure table, so the cap on that table cannot become a "
             "silent omission.\n\n")
    o.append("Stage rows have two kinds and the difference is enforced, not typographic. A "
             "**conformance** row that fails aborts, and S7 fails any run in which a conformance row "
             "reported False yet the run continued. A **disclosure** names a fact about an *authority* "
             "this pipeline must not silently fix (an open finding touching canonical material, a "
             "dangling citation that belongs to `spec/06`); it is printed as `NOTE`, counted in the "
             "artifact, never presented as a pass and never dressed up as a pipeline failure — because "
             "a FAIL that nothing acts on is how a gate trains its reader to ignore FAILs.\n\n")
    o.append("## 6. Relationship to existing governance (§20)\n\n")
    o.append(table([
        ["`Red-on-Rust.md`", "S0 input; read-only, hash-pinned"],
        ["`spec/01` / `spec/02` / `spec/03`", "normative text, section and registry authorities for "
                                              "S1/S2/S5/S6"],
        ["`spec/06` / `spec/09` / `req/03`", "finding, decision and ambiguity registers projected by S4 "
                                            "(never re-graded)"],
        ["`req/` (545 atomic)", "atomic layer of `build/spec/obligations.json`"],
        ["`mod/` / `dep/` / `term/`", "ownership, dependency and terminology authorities (projected, "
                                     "not copied)"],
        ["`audit/`", "12 sha256-pinned historical snapshots, re-verified untouched by S7"],
        ["`final/` / `reg/` / `state/`", "compiled and canonical projections cross-checked by S1/S7"],
        ["`check.py`", "`scripts/spec/_gate.py` is registered as one more checker, so this pipeline is "
                      "gated by the same rule as every other organization"],
    ], ["existing artifact", "relation"]))
    o.append("\nNo identity in any of the above is renamed, renumbered or re-graded by this pipeline, "
             "and no new identifier namespace is added to a register: pipeline-local ids (`VEC-…`) "
             "exist only inside derived build artifacts and are declared additive there.\n\n")
    o.append("## 7. Pre-M0 boundary (§21)\n\n")
    o.append("Forbidden and absent: Rust runtime, CEK, capability kernel, actor, scheduler, host, "
             "persistence, effect and agent implementations. Proof is mechanical rather than "
             "aspirational: S7 walks the tree and fails if any `*.rs` file or `Cargo.toml` exists "
             "(a gate cannot prevent a file from being written, but no run whose tree contains one is "
             "green). A pipeline run writes only under `build/spec/` (gitignored, reproducible), the "
             "committed pointers, `spec/PIPELINE.md` and `TRANSFORMATION-REPORT.md`; the seed source is "
             "opened read-only and every write compares bytes first, so a run with nothing to publish "
             "publishes nothing.\n\n")
    o.append("## 8. Evidence discipline (§22's last boxes)\n\n")
    o.append("Verification PASS proves agreement between projections and authorities — "
             "repository-integrity evidence only. It does not promote a status, does not verify an "
             "obligation, does not lift `REF1-CONDITIONAL` or `V1-CONDITIONAL`, and does not start M0.\n")
    out[PATHS[6]] = o

    return {rel: "".join(lines) for rel, lines in out.items()}
