"""Semantic-module ownership map for the Red-on-Rust specification.

Single source of truth for `mod/18-ownership-matrix.md` and `mod/19-index.json`
(both generated by `mod/_build.py`).

Model (see mod/00-overview.md):
  * 17 semantic modules MOD-01..MOD-17, split by architectural responsibility,
    not by document length.
  * Every one of the 148 canonical obligations (R-...) has exactly ONE canonical
    owner module (R_OWNER).
  * A requirement that spans components keeps its single owner; all other
    components it binds appear as explicit cross-references (R_XREF).
  * Normative text is never re-stated in a second owner's module. Where the
    frozen source itself states the same invariant twice (central invariant vs
    operative statement), the pair is registered in DUPLICATES and both
    statements carry an explicit duplication mark.
  * Atomic records (req/, 545 records) inherit the module of their parent
    obligation; the 16 records with zero or two cited parents are placed
    explicitly in REQ_OVERRIDE with rationale noted in the module files.
"""

MODULES = [
    # (mod-id, domain, title, crate (R-REPO-02), md-file)
    ("MOD-01", "CORE",          "Core semantics, central invariants, trust model",                 "ror-core",                 "01-core.md"),
    ("MOD-02", "COMPILER",      "Compilation boundary (Block to ExecutablePlan)",                  "ror-compiler",             "02-compiler.md"),
    ("MOD-03", "CAPABILITY",    "Capability algebra and capability kernel",                        "ror-kernel",               "03-capability.md"),
    ("MOD-04", "BUDGET",        "Budget algebra and resource accounting",                          "ror-core (+ gates in ror-runtime / ror-kernel)", "04-budget.md"),
    ("MOD-05", "EVALUATOR",     "Explicit CEK evaluation machine",                                 "ror-runtime",              "05-evaluator.md"),
    ("MOD-06", "ACTOR",         "Actor isolation, spawn, mailboxes, marshalling boundary",         "ror-runtime",              "06-actor.md"),
    ("MOD-07", "SCHEDULER",     "Deterministic scheduling and wakeups",                            "ror-runtime",              "07-scheduler.md"),
    ("MOD-08", "EFFECT",        "Effect model and frozen request sequence",                        "ror-runtime (+ durable steps via ror-persistence)", "08-effect.md"),
    ("MOD-09", "HOST",          "Host boundary and replay",                                        "ror-host",                 "09-host.md"),
    ("MOD-10", "SERIALIZATION", "Canonical serialization (15A)",                                   "ror-core (+ vectors/canonical)", "10-serialization.md"),
    ("MOD-11", "PERSISTENCE",   "Durable WAL, snapshots, effect journal (15B)",                    "ror-persistence",          "11-persistence.md"),
    ("MOD-12", "RECOVERY",      "Crash recovery and effect classification",                        "ror-persistence (+ ror-reference oracle)", "12-recovery.md"),
    ("MOD-13", "AGENT",         "LLM / planner boundary",                                          "ror-agent",                "13-agent.md"),
    ("MOD-14", "REFERENCE",     "Independent executable reference model",                          "ror-reference",            "14-reference.md"),
    ("MOD-15", "DIFFERENTIAL",  "Differential harness: generation, comparison, shrinking",         "ror-differential",         "15-differential.md"),
    ("MOD-16", "MUTATION",      "Mutation registry and kill-rate gate",                            "mutations/registry.toml (+ ror-testkit)", "16-mutation.md"),
    ("MOD-17", "VERIFICATION",  "Evidence discipline, test infrastructure, CI, claims, order",     "tests/ + scripts/",        "17-verification.md"),
]
DOMAIN = {m[0]: m[1] for m in MODULES}
FILE_OF = {m[0]: m[4] for m in MODULES}
MOD_OF_DOMAIN = {m[1]: m[0] for m in MODULES}

# ---------------------------------------------------------------------------
# Canonical owner per canonical obligation (R-...).  Exactly one owner each.
# ---------------------------------------------------------------------------
R_OWNER = {}

def _own(mod, prefix, ids):
    for i in ids:
        rid = f"R-{prefix}-{i:02d}"
        assert rid not in R_OWNER, rid
        R_OWNER[rid] = mod

_own("MOD-01", "SCOPE",   [1, 2])
_own("MOD-01", "CORE",    range(1, 11))
_own("MOD-01", "TRUST",   [1, 2, 3])
_own("MOD-01", "ARCH",    [1, 2, 3, 4])
_own("MOD-01", "CALC",    range(1, 9))
_own("MOD-02", "COMPILE", range(1, 6))
_own("MOD-03", "CAP",     range(1, 10))
_own("MOD-03", "KERN",    [1, 2, 3])
_own("MOD-04", "BUDGET",  range(1, 9))
_own("MOD-05", "CEK",     range(1, 8))
_own("MOD-06", "ACTOR",   [1, 2, 3, 5, 6, 8])
_own("MOD-06", "MARSHAL", [1, 2, 3, 4])
_own("MOD-07", "ACTOR",   [4, 7])
_own("MOD-08", "EFFECT",  range(1, 8))
_own("MOD-09", "HOST",    range(1, 6))
_own("MOD-10", "CANON",   range(1, 12))
_own("MOD-11", "PERSIST", range(1, 7))
_own("MOD-11", "DUR",     range(1, 6))
_own("MOD-12", "RECOV",   range(1, 8))
_own("MOD-13", "PLANNER", range(1, 6))
_own("MOD-14", "REF",     [1, 2, 3, 4])
R_OWNER["R-SCOPE-04"] = "MOD-14"
_own("MOD-15", "TEST",    [1, 2, 3, 7])
R_OWNER["R-REF-05"] = "MOD-15"
_own("MOD-16", "TEST",    [4, 5, 6])
_own("MOD-17", "TEST",    [8, 9, 10, 11])
R_OWNER["R-REF-06"] = "MOD-17"
R_OWNER["R-SCOPE-03"] = "MOD-17"
_own("MOD-17", "REPO",    [1, 2, 3])
_own("MOD-17", "ORDER",   range(1, 6))
_own("MOD-17", "CLAIM",   range(1, 5))

# ---------------------------------------------------------------------------
# Cross-references: components a requirement binds without owning.
# Reason strings cite the mechanism, not prose style.
# ---------------------------------------------------------------------------
R_XREF = {
    "R-SCOPE-01": [("MOD-02", "capability-scoped"), ("MOD-04", "resource-bounded"), ("MOD-07", "deterministic"), ("MOD-12", "crash-recoverable")],
    "R-SCOPE-02": [("MOD-17", "status ladder enforced as evidence discipline")],
    "R-CORE-01": [("MOD-13", "planner has no authority"), ("MOD-02", "Block rejected at compiler boundary"), ("MOD-08", "only validated plans reach effect gates")],
    "R-CORE-02": [("MOD-08", "7 conjuncts realized as gates 5..16 of the 16-step sequence (D-12)"), ("MOD-03", "Authorized conjunct"), ("MOD-04", "BudgetAvailable conjunct"), ("MOD-09", "HostPolicyOK conjunct"), ("MOD-11", "Issued conjunct (durable)")],
    "R-CORE-03": [("MOD-03", "predicate owner (D-08)"), ("MOD-08", "gate application")],
    "R-CORE-04": [("MOD-03", "operative owner (D-01)"), ("MOD-06", "cross-actor transfer still bounded by delegation")],
    "R-CORE-05": [("MOD-04", "operative owner (D-02)"), ("MOD-12", "survives crash (R-RECOV-06)"), ("MOD-06", "spawn transfer, not creation")],
    "R-CORE-06": [("MOD-11", "operative owner (D-03)"), ("MOD-08", "sequence position (steps 14 before 16)"), ("MOD-09", "host never invoked earlier")],
    "R-CORE-07": [("MOD-06", "operative owner (D-04)"), ("MOD-03", "delegation is a kernel derive")],
    "R-CORE-08": [("MOD-07", "operative owner (D-05)"), ("MOD-09", "host trace term"), ("MOD-13", "planner trace for end-to-end runs")],
    "R-CORE-09": [("MOD-12", "operative owner (D-06)"), ("MOD-11", "journal classification protocol"), ("MOD-09", "host reconciliation role")],
    "R-CORE-10": [("MOD-12", "operative owner (D-07)"), ("MOD-11", "rejection points that may raise it")],
    "R-TRUST-01": [("MOD-17", "boundary enforcement review"), ("MOD-09", "live host is the only Partial row")],
    "R-TRUST-02": [("MOD-05", "TCB member"), ("MOD-03", "TCB member"), ("MOD-04", "TCB member"), ("MOD-07", "TCB member"), ("MOD-10", "TCB member"), ("MOD-11", "TCB member"), ("MOD-13", "LLM output outside TCB")],
    "R-TRUST-03": [("MOD-03", "operative owner (D-09)"), ("MOD-05", "evaluator must not inspect")],
    "R-ARCH-01": [("MOD-13", "stage 1"), ("MOD-02", "compile stages"), ("MOD-05", "CEK stage"), ("MOD-08", "issuance stage"), ("MOD-11", "durable stage"), ("MOD-09", "host stage")],
    "R-ARCH-02": [("MOD-14", "independent side"), ("MOD-15", "comparison side")],
    "R-ARCH-03": [("MOD-02", "operative owner (D-11)"), ("MOD-05", "no Block path into step()")],
    "R-ARCH-04": [("MOD-17", "enforced via Cargo/visibility rules (R-REPO-03)")],
    "R-CALC-01": [("MOD-05", "consumer of machine Value"), ("MOD-10", "two Value domains collide - U-09")],
    "R-CALC-02": [("MOD-02", "input surface"), ("MOD-05", "evaluated term"), ("MOD-06", "Delegate constructor absent - U-02"), ("MOD-17", "await retraction - U-04")],
    "R-CALC-03": [("MOD-02", "name mapping built here"), ("MOD-05", "symbols only")],
    "R-CALC-04": [("MOD-08", "descriptor used at gates"), ("MOD-10", "digest bytes computed over canonical form"), ("MOD-09", "receipt re-validation")],
    "R-CALC-05": [("MOD-08", "issue/complete_max charging"), ("MOD-04", "escrow accounting")],
    "R-CALC-06": [("MOD-15", "faults compared in differential observation"), ("MOD-12", "RecoveryFault variant"), ("MOD-17", "variant enumeration open - U-08/U-14")],
    "R-CALC-07": [("MOD-09", "replay classes"), ("MOD-12", "recovery classification input"), ("MOD-17", "property table non-normative - U-06")],
    "R-CALC-08": [("MOD-05", "local Sigma"), ("MOD-06", "actor state / global state")],
    "R-COMPILE-01": [("MOD-05", "runtime only receives ExecutablePlan"), ("MOD-13", "proposal enters here")],
    "R-COMPILE-02": [("MOD-17", "open stage question - U-22")],
    "R-COMPILE-03": [("MOD-04", "static bound B vs CostModel"), ("MOD-03", "capability requirements descriptor")],
    "R-COMPILE-04": [("MOD-13", "staleness + PlannerAccepted lifecycle"), ("MOD-03", "authority fixed at t0")],
    "R-COMPILE-05": [("MOD-17", "visibility review")],
    "R-CAP-05": [("MOD-01", "central restatement R-CORE-04 (D-01)"), ("MOD-06", "spawn/delegation derive")],
    "R-CAP-06": [("MOD-08", "gate 6 of 16"), ("MOD-04", "ceiling conjunct cost <= R_A"), ("MOD-01", "central restatement R-CORE-03 (D-08)")],
    "R-CAP-07": [("MOD-06", "delegated envelopes keep lineage")],
    "R-CAP-09": [("MOD-06", "logical time is global state"), ("MOD-04", "deadline comparison"), ("MOD-07", "scheduler steps advance t")],
    "R-KERN-01": [("MOD-10", "CapRef payload 0x30"), ("MOD-11", "capability contexts in snapshots"), ("MOD-06", "marshal rejection target")],
    "R-KERN-02": [("MOD-05", "evaluator calls authorize/derive"), ("MOD-06", "spawn and delegation call derive")],
    "R-KERN-03": [("MOD-01", "central restatement R-TRUST-03 (D-09)"), ("MOD-17", "visibility enforcement review")],
    "R-BUDGET-01": [("MOD-03", "capability ceiling R shares component-wise order"), ("MOD-17", "D semantics open - U-01")],
    "R-BUDGET-04": [("MOD-03", "capability ceiling is the second gate"), ("MOD-08", "gates 7..10 of 16")],
    "R-BUDGET-05": [("MOD-01", "central restatement R-CORE-05 (D-02)"), ("MOD-06", "spawn transfer"), ("MOD-08", "escrow at issuance"), ("MOD-12", "survival after crash")],
    "R-BUDGET-06": [("MOD-07", "scheduler step delta positive"), ("MOD-09", "host interaction delta positive"), ("MOD-17", "per-transition deltas open - U-07")],
    "R-BUDGET-07": [("MOD-02", "static budget bound uses CostModel"), ("MOD-08", "EffectCost is a Cost")],
    "R-BUDGET-08": [("MOD-08", "denial leaves budget unchanged")],
    "R-CEK-01": [("MOD-11", "continuation must be snapshot-serializable"), ("MOD-17", "recursive evaluator prohibited (R-CLAIM-02)")],
    "R-CEK-03": [("MOD-11", "frames need canonical encoding - U-02")],
    "R-CEK-05": [("MOD-16", "mutations M001-M003 target this")],
    "R-CEK-07": [("MOD-15", "progress/preservation exercised differentially")],
    "R-ACTOR-01": [("MOD-03", "isolated capability contexts"), ("MOD-11", "isolated state is snapshot content")],
    "R-ACTOR-02": [("MOD-07", "runnable queue lives here"), ("MOD-04", "global time/deadline"), ("MOD-11", "GlobalSnapshot content")],
    "R-ACTOR-03": [("MOD-11", "counters restored from snapshot"), ("MOD-01", "identity is data, not pointers")],
    "R-ACTOR-05": [("MOD-03", "child capabilities only via derive"), ("MOD-04", "escrow transfer"), ("MOD-02", "BudgetAllocationSpec surface - U-03")],
    "R-ACTOR-06": [("MOD-07", "wakeup enqueues at back"), ("MOD-04", "Receive blocks without fuel")],
    "R-ACTOR-08": [("MOD-01", "corollaries of R-CORE-04/R-CORE-05")],
    "R-MARSHAL-01": [("MOD-10", "recursive rejection over canonical domain"), ("MOD-03", "authority never in ordinary data"), ("MOD-01", "central restatement R-CORE-07 (D-04)")],
    "R-MARSHAL-02": [("MOD-03", "delegation = kernel derive"), ("MOD-02", "Expr::Delegate surface undecided - U-02"), ("MOD-10", "DelegatedCapability envelope encoding")],
    "R-MARSHAL-03": [("MOD-10", "MarshalledValue is canonical bytes; round-trip scope open - AMB-06")],
    "R-MARSHAL-04": [("MOD-10", "traversal over canonical encoding"), ("MOD-03", "explicit delegate() only")],
    "R-ACTOR-04": [("MOD-06", "mailbox wakeup enqueues"), ("MOD-12", "queue reconstructed at recovery"), ("MOD-01", "feeds determinism (D-05)")],
    "R-ACTOR-07": [("MOD-01", "central restatement R-CORE-08 (D-05)"), ("MOD-09", "host trace term"), ("MOD-13", "planner trace term")],
    "R-EFFECT-01": [("MOD-05", "Request yields EffectRequest"), ("MOD-09", "host receives only issued requests")],
    "R-EFFECT-02": [("MOD-03", "AuthOK is kernel Authorized"), ("MOD-04", "BudgetOK is dual gate")],
    "R-EFFECT-03": [("MOD-03", "steps 5..7"), ("MOD-04", "steps 8..10, 13"), ("MOD-11", "step 14 durable issuance"), ("MOD-07", "step 15 Pending status"), ("MOD-09", "step 16 host invocation"), ("MOD-01", "refines external-effect chain (D-12)")],
    "R-EFFECT-04": [("MOD-03", "gate not called"), ("MOD-04", "budget unchanged"), ("MOD-11", "log unchanged"), ("MOD-09", "host never called")],
    "R-EFFECT-05": [("MOD-04", "escrow partition arithmetic"), ("MOD-11", "escrow must be durable")],
    "R-EFFECT-06": [("MOD-09", "receipt produced by host/replay"), ("MOD-10", "bytes underlying both digests"), ("MOD-11", "journal integrity M017")],
    "R-EFFECT-07": [("MOD-04", "charge/release/refund"), ("MOD-11", "EffectCompleted record appended"), ("MOD-05", "continuation resume")],
    "R-HOST-01": [("MOD-08", "gate 11 is fail-early twin"), ("MOD-01", "chain conjunct")],
    "R-HOST-02": [("MOD-08", "only issued effects escape"), ("MOD-11", "durable issuance precedes")],
    "R-HOST-03": [("MOD-11", "trace sourced from durable journal"), ("MOD-10", "digests recomputed/validated"), ("MOD-12", "replay used by recovery checks")],
    "R-HOST-04": [("MOD-12", "recovery is replay over durable records"), ("MOD-15", "live-vs-replay differential"), ("MOD-13", "end-to-end replay with recorded proposal")],
    "R-HOST-05": [("MOD-15", "trace comparison obligation")],
    "R-CANON-01": [("MOD-11", "no secondary serialization"), ("MOD-06", "marshalling uses this format")],
    "R-CANON-09": [("MOD-08", "EffectDigest identity"), ("MOD-11", "state_digest / checksums"), ("MOD-09", "replay validation")],
    "R-CANON-10": [("MOD-15", "evidence scoped to generated distribution"), ("MOD-17", "claim discipline")],
    "R-CANON-11": [("MOD-17", "M1 gate consumes vectors")],
    "R-PERSIST-01": [("MOD-10", "payloads strictly 15A")],
    "R-PERSIST-02": [("MOD-10", "payload layer is 15A"), ("MOD-12", "rejections surface at recovery")],
    "R-PERSIST-03": [("MOD-07", "ActorSelected et al. are envelope events"), ("MOD-17", "EventSequence vs WalSequence open - U-16")],
    "R-PERSIST-04": [("MOD-05", "EvalState/continuation content"), ("MOD-06", "actor state content"), ("MOD-03", "capability contexts durable"), ("MOD-07", "runnable queue content"), ("MOD-10", "machine-state encoding unfrozen - U-02")],
    "R-PERSIST-05": [("MOD-12", "recovery ignores invalid snapshots"), ("MOD-10", "digest over canonical bytes")],
    "R-PERSIST-06": [("MOD-12", "gap detected during recovery")],
    "R-DUR-01": [("MOD-01", "central restatement R-CORE-06 (D-03)"), ("MOD-08", "steps 14/16"), ("MOD-09", "invocation precondition")],
    "R-DUR-02": [("MOD-08", "transaction sits inside the request sequence"), ("MOD-10", "record payloads are 15A bytes")],
    "R-DUR-03": [("MOD-08", "receipt digests continue the chain"), ("MOD-12", "journal reconstructed and causality-checked")],
    "R-DUR-04": [("MOD-12", "classification applied at T1..T4"), ("MOD-08", "escrow semantics at issuance")],
    "R-DUR-05": [("MOD-04", "escrow partition owner"), ("MOD-12", "post-recovery invariant check")],
    "R-RECOV-01": [("MOD-11", "D components durable"), ("MOD-15", "recovery differential compares")],
    "R-RECOV-02": [("MOD-11", "rows mirror journal causality"), ("MOD-17", "M10 gate executes the matrix")],
    "R-RECOV-03": [("MOD-10", "decode via 15A"), ("MOD-07", "queue reconstruction"), ("MOD-04", "conservation re-validated")],
    "R-RECOV-04": [("MOD-14", "independent recovery oracle"), ("MOD-17", "anti-oracle-collapse review")],
    "R-RECOV-05": [("MOD-11", "detection points"), ("MOD-01", "central restatement R-CORE-10 (D-07)")],
    "R-RECOV-06": [("MOD-04", "invariant statement"), ("MOD-11", "escrow records carry it over")],
    "R-RECOV-07": [("MOD-09", "authoritative host reconciliation protocol"), ("MOD-11", "EffectReconciled record"), ("MOD-17", "outcome variants open - U-15")],
    "R-PLANNER-01": [("MOD-02", "block enters compile pipeline"), ("MOD-01", "LLMOutput is Data")],
    "R-PLANNER-02": [("MOD-03", "cannot allocate/authorize"), ("MOD-04", "cannot modify budgets"), ("MOD-07", "cannot touch scheduler"), ("MOD-06", "cannot allocate actors"), ("MOD-09", "cannot invoke host"), ("MOD-02", "cannot bypass compilation"), ("MOD-11", "cannot bypass persistence")],
    "R-PLANNER-03": [("MOD-02", "checked before compilation"), ("MOD-11", "epoch compared against durable log state")],
    "R-PLANNER-04": [("MOD-11", "PlannerAccepted recorded durably"), ("MOD-09", "replay consumes recorded proposal"), ("MOD-07", "determinism theorem term")],
    "R-PLANNER-05": [("MOD-17", "harness side (ror-testkit)"), ("MOD-09", "ReplayHost for end-to-end replay"), ("MOD-02", "compiler rejection case 1")],
    "R-REF-01": [("MOD-15", "gate executed here"), ("MOD-12", "recovery equivalence conjunct"), ("MOD-17", "acceptance R-TEST-11")],
    "R-REF-02": [("MOD-05", "forbidden dep"), ("MOD-03", "forbidden dep"), ("MOD-04", "forbidden dep"), ("MOD-07", "forbidden dep"), ("MOD-10", "forbidden dep"), ("MOD-11", "forbidden dep"), ("MOD-09", "forbidden dep"), ("MOD-17", "dependency review")],
    "R-REF-03": [("MOD-05", "CEK modeled"), ("MOD-03", "algebra modeled"), ("MOD-04", "budgets modeled"), ("MOD-06", "actors/marshalling modeled"), ("MOD-07", "scheduler modeled"), ("MOD-08", "effects modeled"), ("MOD-11", "persistence modeled"), ("MOD-12", "recovery modeled")],
    "R-REF-04": [("MOD-17", "non-goals bound claims")],
    "R-SCOPE-04": [("MOD-15", "fixtures may be shared, transitions never")],
    "R-REF-05": [("MOD-14", "reference emits normalized Observation"), ("MOD-17", "first divergence feeds adjudication")],
    "R-TEST-01": [("MOD-17", "CI cadence consumes modes (R-TEST-10)")],
    "R-TEST-02": [("MOD-17", "artifact consumed by adjudication")],
    "R-TEST-07": [("MOD-16", "mutation coverage tagged"), ("MOD-17", "coverage report consumed in CI")],
    "R-TEST-04": [("MOD-05", "M001..M003"), ("MOD-03", "M004..M006"), ("MOD-04", "M007/M009"), ("MOD-11", "M008/M015/M016"), ("MOD-08", "M010/M017/M018"), ("MOD-07", "M011/M012"), ("MOD-06", "M013"), ("MOD-10", "M014")],
    "R-TEST-05": [("MOD-17", "release-blocking rule"), ("MOD-15", "kill evidence gathered differentially")],
    "R-TEST-06": [("MOD-17", "framework self-test infrastructure"), ("MOD-15", "oracle used to prove kills")],
    "R-TEST-08": [("MOD-12", "classification semantics"), ("MOD-11", "crash points T0..T6 defined at issuance")],
    "R-TEST-09": [("MOD-15", "divergences originate here"), ("MOD-01", "specification ambiguity reopens frozen text (R-SCOPE-03)")],
    "R-TEST-10": [("MOD-16", "mutation gate stage"), ("MOD-15", "differential suites staged")],
    "R-TEST-11": [("MOD-15", "oracle equality conjunct"), ("MOD-16", "kill-rate conjunct"), ("MOD-12", "recovery-equivalence conjunct")],
    "R-REF-06": [("MOD-08", "gates mocked/asserted"), ("MOD-03", "exactly-once kernel calls asserted"), ("MOD-15", "doubles run inside differential harness")],
    "R-SCOPE-03": [("MOD-01", "applies to all frozen semantics; adjudication enforces it (R-TEST-09, this module)")],
    "R-REPO-02": [("MOD-01", "ror-core contract"), ("MOD-02", "ror-compiler contract"), ("MOD-03", "ror-kernel contract"), ("MOD-05", "ror-runtime contract"), ("MOD-11", "ror-persistence contract"), ("MOD-09", "ror-host contract"), ("MOD-13", "ror-agent contract"), ("MOD-14", "ror-reference contract"), ("MOD-15", "ror-differential contract"), ("MOD-16", "ror-testkit / mutations registry")],
    "R-ORDER-03": [("MOD-02", "Block =/> ExecutablePlan"), ("MOD-03", "CapRef =/> AuthorityInspection"), ("MOD-06", "capability =/> ordinary transfer"), ("MOD-11", "host after durable issuance")],
}

# ---------------------------------------------------------------------------
# Explicitly marked duplications / overlaps (register; see mod/00-overview.md).
# kind: central = verbatim central restatement; refinement = abstract chain vs
# realization; distribution = one invariant, several enforcement points.
# ---------------------------------------------------------------------------
DUPLICATES = [
    ("D-01", "central",      ["R-CORE-04", "R-CAP-05"],   "R-CAP-05",   "No authority amplification stated centrally (README thesis) and in the algebra v0.2; algebraic statement is canonical."),
    ("D-02", "central",      ["R-CORE-05", "R-BUDGET-05"], "R-BUDGET-05", "Budget partition conservation stated centrally and in the budget model; budget-model statement is canonical."),
    ("D-03", "central",      ["R-CORE-06", "R-DUR-01"],   "R-DUR-01",   "HostInvoked => DurableIssued stated centrally and at the durability boundary; boundary statement is canonical."),
    ("D-04", "central",      ["R-CORE-07", "R-MARSHAL-01"], "R-MARSHAL-01", "Raw-capability marshal rejection stated centrally and at the actor marshalling boundary; marshalling statement is canonical."),
    ("D-05", "central",      ["R-CORE-08", "R-ACTOR-07"], "R-ACTOR-07", "Deterministic-concurrency theorem stated centrally and at Phase 13; Phase 13 theorem is canonical."),
    ("D-06", "central",      ["R-CORE-09", "R-RECOV-02", "R-RECOV-03"], "R-RECOV-02", "Qualified crash-recovery theorem stated centrally; the T0..T6 matrix + algorithm are the canonical operative form."),
    ("D-07", "central",      ["R-CORE-10", "R-RECOV-05"], "R-RECOV-05", "No-silent-repair rule stated centrally and at recovery; recovery statement is canonical."),
    ("D-08", "distribution", ["R-CORE-03", "R-CAP-06", "R-EFFECT-02"], "R-CAP-06", "No unauthorized effects: canonical predicate in the algebra, enforced by the gated transition form and gate 6."),
    ("D-09", "central",      ["R-TRUST-03", "R-KERN-03"], "R-KERN-03", "No hidden authority stated as trust rule and as kernel visibility rule; kernel visibility statement is canonical."),
    ("D-10", "verbatim",     ["R-SCOPE-04", "R-REF-02"],  "R-REF-02",   "Zero shared core logic stated in master prompt 1.2 and as the 15C.3 independence boundary; the boundary enumeration is canonical. Intra-module (both MOD-14)."),
    ("D-11", "distribution", ["R-ARCH-03", "R-COMPILE-01", "R-COMPILE-05"], "R-COMPILE-01", "Block has no path into step(): architectural statement vs compiler constructor privacy; compiler statement is canonical."),
    ("D-12", "refinement",   ["R-CORE-02", "R-EFFECT-03"], "R-EFFECT-03", "7-conjunct external-effect chain vs frozen 16-step request sequence (conjuncts realized by gates 5..16); the sequence is canonical."),
]

# Atomic records whose SOURCE cites zero or two parent obligations:
# placed explicitly, rationale recorded in target module file.
REQ_OVERRIDE = {
    "REQ-COMPILE-014": "MOD-02",  # U-22 gap note (v1 J2 inference absence)
    "REQ-CALC-020":    "MOD-01",  # v0.3 pure E-Let/E-Seq/E-If rules with delta_t = 0
    "REQ-CEK-022":     "MOD-05",  # v0.3 E-Call budget premises
    "REQ-CAP-022":     "MOD-03",  # v0.3 E-Attenuate (Valid + AdmissibleConstraint)
    "REQ-CAP-023":     "MOD-03",  # v0.3 E-AttenuateDenied
    "REQ-CAP-024":     "MOD-03",  # AdmissibleConstraint premise status (AMB-12)
    "REQ-KERN-006":    "MOD-03",  # parents R-KERN-02 + R-KERN-03 (privacy)
    "REQ-KERN-009":    "MOD-03",  # parents R-TRUST-03 + R-KERN-01 (evaluator exclusion set)
    "REQ-BUDGET-008":  "MOD-04",  # D semantics (AMB-01 / U-01)
    "REQ-BUDGET-032":  "MOD-04",  # fault transitions preserve C and R
    "REQ-EFFECT-037":  "MOD-08",  # v0.3 E-Request success premises
    "REQ-EFFECT-038":  "MOD-08",  # v0.3 E-RequestDenied precedence
    "REQ-EFFECT-039":  "MOD-08",  # v0.3 E-Receipt
    "REQ-EFFECT-040":  "MOD-08",  # v0.3 E-ReceiptMismatch
    "REQ-ACTOR-024":   "MOD-06",  # v0.3 E-Spawn
    "REQ-ACTOR-035":   "MOD-06",  # RunState vs ActorStatus (C-18)
}

# Mutation registry M001..M018 -> module whose owned obligations it targets.
MUTANT_MODULE = {
    "M001": "MOD-05", "M002": "MOD-05", "M003": "MOD-05",
    "M004": "MOD-03", "M005": "MOD-03", "M006": "MOD-03",
    "M007": "MOD-04", "M008": "MOD-11", "M009": "MOD-04",
    "M010": "MOD-08",
    "M011": "MOD-07", "M012": "MOD-07",
    "M013": "MOD-06",
    "M014": "MOD-10",
    "M015": "MOD-11", "M016": "MOD-11",
    "M017": "MOD-08", "M018": "MOD-08",
}
MUTANT_TARGET = {
    "M001": "R-CEK-05 (LTR)", "M002": "R-CEK-05 (arity precheck)", "M003": "R-CEK-05 (function check)",
    "M004": "R-CAP-07 / R-CORE-03 (revocation)", "M005": "R-CAP-06 (ceiling conjunct)", "M006": "R-CAP-05 / R-CORE-04 (amplification)",
    "M007": "R-BUDGET-04 / R-BUDGET-08 (budget gate)", "M008": "R-DUR-05 (indeterminate escrow)", "M009": "R-BUDGET-02 (checked arithmetic)",
    "M010": "R-EFFECT-03/04 (gate ordering)",
    "M011": "R-ACTOR-04 (blocked not scheduled)", "M012": "R-ACTOR-04 (at-most-once membership)",
    "M013": "R-ACTOR-06 (mailbox FIFO)",
    "M014": "R-CANON-06 (duplicate map keys)",
    "M015": "R-PERSIST-06 (WAL gap)", "M016": "R-PERSIST-02 (checksum)",
    "M017": "R-EFFECT-06 / R-DUR-03 (digest)", "M018": "R-EFFECT-06 (receipt resume)",
}

# Frozen verification-obligation tags (spec/08 section 1) -> verifying module.
TAG_MODULE = {
    "CEK-CALL-ARITY-PRECHECK": "MOD-05",
    "CEK-CALL-ARGS-LTR": "MOD-05",
    "CEK-CLOSURE-LEXICAL-CAPTURE": "MOD-05",
    "CAP-DERIVE-NO-AMPLIFICATION": "MOD-03",
    "CAP-REVOCATION-ANCESTOR": "MOD-03",
    "BUDGET-CONSUMPTION-CONSERVATION": "MOD-04",
    "BUDGET-ESCROW-CONSERVATION": "MOD-11",
    "EFFECT-ISSUE-DURABLE-BEFORE-HOST": "MOD-11",
    "EFFECT-RECEIPT-DIGEST-VALIDATION": "MOD-08",
    "SCHED-FIFO": "MOD-07",
    "SCHED-BLOCKED-NOT-SCHEDULED": "MOD-07",
    "MARSHAL-NO-RAW-CAPABILITY": "MOD-06",
    "WAL-SEQUENCE-CONTINUITY": "MOD-11",
    "WAL-GAP-REJECT": "MOD-11",
    "RECOVERY-ISSUED-INDETERMINATE": "MOD-12",
    "SNAPSHOT-COMMIT-INTEGRITY": "MOD-11",
}

# Milestone gate M0..M11 -> modules whose evidence gates it binds (mod/00).
MILESTONE_MODULE = {
    "M0":  ["MOD-17"],
    "M1":  ["MOD-10"],
    "M2":  ["MOD-05", "MOD-14", "MOD-15"],
    "M3":  ["MOD-05"],
    "M4":  ["MOD-03", "MOD-14"],
    "M5":  ["MOD-08", "MOD-11", "MOD-09"],
    "M6":  ["MOD-06", "MOD-07"],
    "M7":  ["MOD-11", "MOD-12"],
    "M8":  ["MOD-15", "MOD-14"],
    "M9":  ["MOD-16"],
    "M10": ["MOD-12", "MOD-17"],
    "M11": ["MOD-17"],
}

# spec/09 unresolved items -> modules they affect (non-owning; decision items).
U_AFFECTED = {
    "U-01": ["MOD-04"], "U-02": ["MOD-10", "MOD-11", "MOD-06", "MOD-02"],
    "U-03": ["MOD-06", "MOD-04"], "U-04": ["MOD-01", "MOD-05"],
    "U-05": ["MOD-06", "MOD-01"], "U-06": ["MOD-08", "MOD-09", "MOD-12"],
    "U-07": ["MOD-04", "MOD-07", "MOD-09"], "U-08": ["MOD-01"],
    "U-09": ["MOD-01", "MOD-10", "MOD-03"], "U-13": ["MOD-13"],
    "U-14": ["MOD-01"], "U-15": ["MOD-12"],
    "U-16": ["MOD-11"], "U-17": ["MOD-11", "MOD-12", "MOD-07"],
    "U-21": ["MOD-01", "MOD-03", "MOD-10"], "U-22": ["MOD-02"],
}
